---
title: "Squemous_Stage_Candida_comparison"
author: "Dipankor Dhrubo"
date: "2026-02-10"
output: html_document
---

```{r setup, include=FALSE}
library(tableone)
library(knitr)
library(tidyverse)
library(umap)
library(survival)
library(survminer)
library(mt.surv)
library(ggsurvfit)
library(mt.surv)
library(DESeq2)
```

```{r}
Squemous_Metadata<- read_rds("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/NSCLC_metadata.rds") %>%
  filter(Histology == "Squamous Cell Carcinoma") %>% filter(!Stage == "Unknown") %>% droplevels() %>%
  mutate(Stage_type = ifelse(
    Stage %in% c("I","II","III"),"Local","Advanced")) %>% unique() %>%
  filter(Primary_Met == "Primary")

Specimen<- bind_rows(read.csv("/fs/ess/PDE0023/microbiomeRIG/2023_11_30/Clinical_Data/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20230620_ClinicalMolLinkage_V4.csv"),
                          read.csv("/fs/ess/PDE0023/microbiomeRIG/2024_05_01/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20240221_ClinicalMolLinkage_V4.csv")) %>%
  select(RNASeq,SpecimenSiteOfCollection) %>% filter(RNASeq %in% Squemous_Metadata$sample)

## Selecting Only lung specific samples

lung_keywords <- c("lung", "Lung", "bronchus", "Bronchus", "trachea", "Trachea")

# Keep rows where Specimen_site contains any of the lung-related keywords
lung_sites <- Specimen %>%
  filter(grepl(paste(lung_keywords, collapse = "|"), SpecimenSiteOfCollection, ignore.case = TRUE)) %>% pull(RNASeq)

Squemous_Metadata <- Squemous_Metadata %>% filter(sample %in% lung_sites) %>% unique()


## Reannotating CAlevel

Clinical<- Squemous_Metadata %>% select(sample,diagsurvtime,status) %>%
  dplyr::rename(vitalstatus = status) %>% mutate(days = as.numeric(diagsurvtime)) %>%
  select(-diagsurvtime,sample, days, vitalstatus)

Candida_count<- Squemous_Metadata %>% select(sample,Normalize_Candida) 

survoutput <- mt.surv::survivalByQuantile("Normalize_Candida", Candida_count, Clinical)


# Removing the NA value

survoutput<- survoutput[complete.cases(survoutput),]

# Creating the plot

survoutput %>% 
  ggplot(aes(x = percentile, y = -log10(pval), color = hazard.direction)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") +
  theme_bw()

Squemous_survival<- Squemous_Metadata %>% select(sample, Stage_type, diagsurvtime, status, CAlevel) %>% 
  unique() %>% mutate(Stage_type = factor(Stage_type, levels=c("Local","Advanced")))

survfit2(Surv(diagsurvtime, status) ~ Stage_type, data = Squemous_survival) |>
  ggsurvfit(linewidth = 1) +
  labs(title = "NSCLC: Stage",
       x = "Time (Years)")+
      theme_bw() + add_pvalue(size = 5)+
  theme(
    axis.title.x = element_text(size = 14),  # Increase y-axis text size
    axis.title.y = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.title = element_text(size = 14), 
    legend.position = c(0.275, 0.2)
  ) +
  add_confidence_interval() +
  scale_ggsurvfit() +
  xlim(0, 10) 

  ggsave("../figures/KMcurve_PrimaryMet_minusRadiation_1000.png", width = 6, height = 4)

  
  fit<- coxph(Surv(diagsurvtime, status) ~ CAlevel*Stage, data = Squemous_Metadata)

  summary(fit)
  
```


```{r}
### All Stages Comparison

df <- Squemous_Metadata %>%
  filter(!is.na(Stage), !is.na(CAlevel),
         !is.na(diagsurvtime), !is.na(status)) %>%
  mutate(
    CAlevel = factor(CAlevel, levels = c("Low","High")),
    Stage   = factor(Stage)
  ) %>%
  droplevels()

df<- as.data.frame(df)

fit <- survfit(Surv(diagsurvtime, status) ~ CAlevel, data = df)

p <- ggsurvplot_facet(
  fit,
  data     = df,
  facet.by = "Stage",
  pval     = TRUE,
  risk.table = TRUE,
  xlim     = c(0, 10),
  break.x.by = 1,
  xlab     = "Time (years)",
  conf.int = TRUE,
  conf.int.alpha = 0.25,
  palette  = c("#E7B800", "#2E9FDF"),
  legend.title = "Candida",
  legend.labs  = c("Low", "High"),
  ggtheme = theme_bw()
)

p

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Squamous/Stages_comparison.png",p, width = 6, height = 4)


```


```{r}
Squamous_radiation <- Squemous_Metadata %>% filter(RadiationTherapyInd == "Yes") %>% filter(Histology == "Squamous Cell Carcinoma") %>% filter(!Stage == "Unknown") %>% 
  mutate(Stage_type = ifelse(
    Stage %in% c("I","II","III"),"Local","Advanced")) %>% unique()

## Reannotating CAlevel

Clinical<- Squamous_radiation %>% select(sample,diagsurvtime,status) %>%
  dplyr::rename(vitalstatus = status) %>% mutate(days = as.numeric(diagsurvtime)) %>%
  select(-diagsurvtime,sample, days, vitalstatus)

Candida_count<- Squamous_radiation %>% select(sample,Normalize_Candida) 

survoutput <- mt.surv::survivalByQuantile("Normalize_Candida", Candida_count, Clinical)


# Removing the NA value

survoutput<- survoutput[complete.cases(survoutput),]

# Creating the plot

survoutput %>% 
  ggplot(aes(x = percentile, y = -log10(pval), color = hazard.direction)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") +
  theme_bw()


Squa_survival_rad<- Squamous_radiation %>% select(sample, Stage_type, diagsurvtime, status, CAlevel) %>% 
  unique() %>% mutate(Stage_type = factor(Stage_type, levels=c("Local","Advanced")))

survfit2(Surv(diagsurvtime, status) ~ CAlevel, data = Squa_survival_rad %>% filter(Stage_type == "Advanced") ) |>
  ggsurvfit(linewidth = 1) +
  labs(title = "NSCLC: Advanced (Stage IV)",
       x = "Time (Years)")+
      theme_bw() + add_pvalue(size = 5)+
  theme(
    axis.title.x = element_text(size = 14),  # Increase y-axis text size
    axis.title.y = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.title = element_text(size = 14), 
    legend.position = c(0.275, 0.2)
  ) +
  add_confidence_interval() +
  scale_ggsurvfit() +
  xlim(0, 10) 

  ggsave("../figures/KMcurve_PrimaryMet_minusRadiation_1000.png", width = 6, height = 4)

  
  fit<- coxph(Surv(diagsurvtime, status) ~ CAlevel*Stage, data = Squamous_radiation)

  summary(fit)


```

```{r}
### All Stages Comparison for radiation patients only

df <- Squemous_Metadata %>%
  filter(!is.na(Stage), !is.na(CAlevel),
         !is.na(diagsurvtime), !is.na(status)) %>%
  mutate(
    CAlevel = factor(CAlevel, levels = c("Low","High")),
    Stage   = factor(Stage)
  ) %>%
  droplevels() %>%
  filter(RadiationTherapyInd == "Yes")

df<- as.data.frame(df)

fit <- survfit(Surv(diagsurvtime, status) ~ CAlevel, data = df)


p <- ggsurvplot_facet(
  fit,
  data           = df,
  facet.by       = "Stage",
  pval           = TRUE,
  risk.table     = TRUE,
  xlim           = c(0, 10),
  break.x.by     = 1,
  xlab           = "Time (years)",
  conf.int       = TRUE,
  conf.int.style = "ribbon",
  conf.int.alpha = 0.25,
  conf.int.fill  = "grey70",
  palette        = c("#E7B800", "#2E9FDF"),
  legend.title   = "Candida",
  legend.labs    = c("Low", "High"),
  linetype       = 1,    # <- fixes the ribbon error
  size           = 0.7,  # optional
  ggtheme        = theme_bw()
)
p


p

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Squamous/Stages_comparison_radiation.png",p, width = 6, height = 4)


```


```{r}
### PDL1 expression comparison
Metadata<- read_rds("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/NSCLC_metadata.rds") %>% unique()
   filter(!Stage == "Unknown") %>% 
  mutate(Stage_type = ifelse(
    Stage %in% c("I","II","III"),"Local","Advanced")) %>% unique()

Specimen<- bind_rows(read.csv("/fs/ess/PDE0023/microbiomeRIG/2023_11_30/Clinical_Data/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20230620_ClinicalMolLinkage_V4.csv"),
                          read.csv("/fs/ess/PDE0023/microbiomeRIG/2024_05_01/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20240221_ClinicalMolLinkage_V4.csv")) %>%
  select(RNASeq,SpecimenSiteOfCollection) %>% filter(RNASeq %in% Metadata$sample)

## Selecting Only lung specific samples

lung_keywords <- c("lung", "Lung", "bronchus", "Bronchus", "trachea", "Trachea")

# Keep rows where Specimen_site contains any of the lung-related keywords
lung_sites <- Specimen %>%
  filter(grepl(paste(lung_keywords, collapse = "|"), SpecimenSiteOfCollection, ignore.case = TRUE)) %>% pull(RNASeq)

Metadata <- Metadata %>% filter(sample %in% lung_sites) %>% unique()

NSCLC_expression<- readRDS("/fs/ess/PAS1695/projects/exotho/data/Digital_Twins/NSCLC_processed_gene_expression.rds") %>% rownames_to_column(var = "Gene")

PDL1_gene<- NSCLC_expression %>% filter(Gene == "CD274") %>% select(-1) %>% t() %>% as.data.frame()

PDL1_gene <- PDL1_gene %>% rownames_to_column(var = "sample") %>% dplyr::rename(CD274 = V1) 
PDL1_gene <- PDL1_gene %>% filter(sample %in% Metadata$sample)

PDL1_gene$CD274<- log2(PDL1_gene$CD274 + 1)

Clinical<- Metadata %>% filter(sample %in% PDL1_gene$sample) %>% select(sample,diagsurvtime,status) %>%
  dplyr::rename(vitalstatus = status) %>% mutate(days = as.numeric(diagsurvtime)) %>%
  select(-diagsurvtime,sample, days, vitalstatus) %>% unique()

PDL_count<- PDL1_gene %>% select(sample,CD274) 

all((Clinical$sample) == PDL_count$sample)

survoutput <- mt.surv::survivalByQuantile("CD274", PDL_count, Clinical)


# Removing the NA value

survoutput<- survoutput[complete.cases(survoutput),]

# Creating the plot

survoutput %>% 
  ggplot(aes(x = percentile, y = -log10(pval), color = hazard.direction)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") +
  theme_bw()

##
PDL1_gene <- PDL1_gene %>% mutate(CD274_Status = ifelse(CD274 < 9.757579, "Low_PDL1","High_PDL1" ))

Metadata <- Metadata %>% left_join(PDL1_gene, by= "sample")

survfit2(Surv(diagsurvtime, status) ~ CD274_Status, data = Metadata ) |>
  ggsurvfit(linewidth = 1) +
  labs(title = "NSCLC:PDL1",
       x = "Time (Years)")+
      theme_bw() + add_pvalue(size = 5)+
  theme(
    axis.title.x = element_text(size = 14),  # Increase y-axis text size
    axis.title.y = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.title = element_text(size = 14), 
    legend.position = c(0.275, 0.2)
  ) +
  add_confidence_interval() +
  scale_ggsurvfit() +
  xlim(0, 10) 



### Comparing the High low CA in High low PDL1

Squamous_Metadata<- Metadata %>% filter(Histology == "Squamous Cell Carcinoma") %>% unique()

df <- Squamous_Metadata %>%
  filter(!is.na(Stage), !is.na(CAlevel),
         !is.na(diagsurvtime), !is.na(status)) %>%
  mutate(
    CAlevel = factor(CAlevel, levels = c("Low","High")),
    Stage   = factor(Stage),
    CD274_Status = factor(CD274_Status, levels=c("Low_PDL1","High_PDL1"))
  ) %>%
  droplevels() %>%
  filter(RadiationTherapyInd == "Yes")

df<- as.data.frame(df)

fit <- survfit(Surv(diagsurvtime, status) ~ CAlevel, data = df)

p <- ggsurvplot_facet(
  fit,
  data       = df,
  facet.by   = "CD274_Status",
  pval       = TRUE,
  risk.table = TRUE,
  xlim       = c(0, 10),
  break.x.by = 1,
  xlab       = "Time (years)",
  conf.int   = T,                 # <-- key fix
  palette    = c("#E7B800", "#2E9FDF"),
  legend.title = "Candida",
  legend.labs  = c("Low", "High"),
  size       = 0.7,
  ggtheme    = theme_bw()
)
p
 

library(survival)
library(dplyr)

df2 <- Squamous_Metadata %>%
  filter(!is.na(diagsurvtime), !is.na(status),
         !is.na(CAlevel), !is.na(CD274_Status), !is.na(Stage)) %>%
  mutate(
    CAlevel = factor(CAlevel, levels = c("Low","High")),
    CD274_Status = factor(CD274_Status, levels = c("Low_PDL1","High_PDL1")),
    Stage = factor(Stage, levels = c("I","II","III","IV"))
  )

fit_main <- coxph(
  Surv(diagsurvtime, status) ~ CAlevel + CD274_Status + Stage,
  data = df
)

summary(fit_main)

fit_int <- coxph(
  Surv(diagsurvtime, status) ~ Stage + CAlevel * CD274_Status,
  data = df
)

summary(fit_int)

coxph(
  Surv(diagsurvtime, status) ~ Stage + Histology + CAlevel*CD274_Status*Histology,
  data = Metadata %>% filter(RadiationTherapyInd == "Yes") %>% mutate(CD274_Status = factor(CD274_Status, levels=c("Low_PDL1","High_PDL1"))
  ))
)


```

```{r}
Squom_Metadata<- read_rds("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/NSCLC_metadata.rds") %>%
  
  filter(Histology == "Squamous Cell Carcinoma") %>% filter(!Stage == "Unknown") %>% unique()

Squom_samples<- Squom_Metadata$AvatarKey %>% unique()

Clinical_data_Squam <-bind_rows(read.csv("/fs/ess/PDE0023/microbiomeRIG/2023_11_30/Clinical_Data/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20230620_Diagnosis_V4.csv"),read.csv("/fs/ess/PDE0023/microbiomeRIG/2024_05_01/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20240221_Diagnosis_V4.csv"))

Clinical_data_Squam <- Clinical_data_Squam %>% filter(AvatarKey %in% Squom_samples) %>%
  select(AvatarKey, AgeAtFirstContact,PrimaryDiagnosisSite, ClinGroupStage, CurrentlySeenForPrimaryOrRecurr)

Linkage<- bind_rows(read.csv("/fs/ess/PDE0023/microbiomeRIG/2023_11_30/Clinical_Data/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20230620_ClinicalMolLinkage_V4.csv"),read.csv("/fs/ess/PDE0023/microbiomeRIG/2024_05_01/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20240221_ClinicalMolLinkage_V4.csv"))

Linkage <- Linkage %>% filter(ORIENAvatarKey %in% Squom_samples) %>% select(ORIENAvatarKey,Disease.Type, SpecimenSiteOfOrigin, SpecimenSiteOfCollection, Primary.Met, 
                                                                            Histology.Behavior, Age.At.Specimen.Collection)
names(Linkage)[1] <- "AvatarKey"

Radiation<- bind_rows(read.csv("/fs/ess/PDE0023/microbiomeRIG/2023_11_30/Clinical_Data/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20230620_Radiation_V4.csv"),read.csv("/fs/ess/PDE0023/microbiomeRIG/2024_05_01/20PRJ060OSU_NormalizedFiles/20PRJ060OSU_20240221_Radiation_V4.csv"))

Radiation<- Radiation %>% filter(AvatarKey %in% Squom_samples) %>% select(AvatarKey,RadiationTherapyInd,
                                                                           RadSite,RadTreatmentLine,LymphNodeRadiation, RadModality) 

Clinical_data_Squam <-  Clinical_data_Squam %>% left_join(Linkage, by = "AvatarKey") %>% unique()
Clinical_data_Squam <- Clinical_data_Squam %>% left_join(Radiation, by = "AvatarKey") %>% unique()
Clinical_data_Squam <- Clinical_data_Squam %>% unique()

writexl::write_xlsx(Clinical_data_Squam,"/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/Squamous/Clinical_data_Squam.xlsx")

```




