---
title: "KmPlot_Analysis"
author: "Dipankor Dhrubo"
date: "2025-09-19"
output: html_document
---

```{r setup, include=FALSE}
library(tableone)
library(knitr)
library(tidyverse)
library(survminer)
library(survival)
library(mt.surv)

```


```{r}
#reading in the data from 00_processing_clinical_CRCORIEN2025.Rmd script 

processed <- read_rds("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/Lung_resampled_data.rds")


```

```{r}
# mtsurv plot generation

Clinical <- processed %>%
  select(sample, diagsurvtime, status) %>%
  dplyr::rename(vitalstatus = status) %>% mutate(days = as.numeric(diagsurvtime)) %>%
  select(-diagsurvtime,sample, days, vitalstatus)

Clinical<-Clinical[,c(1,3,2)] # Make sure you look at the dataframe first to select the correct columns.

Abundance_data<- processed %>% select(sample,Candida)

survoutput <- mt.surv::survivalByQuantile("Candida", Abundance_data, Clinical)

# Removing the NA value

survoutput<- survoutput[complete.cases(survoutput),]

# Creating the plot

survoutput %>% 
  ggplot(aes(x = percentile, y = -log10(pval), color = hazard.direction)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") +
  theme_bw()


ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/ORIEN_NSCLC_candida_mtsurv.png", height = 3, width = 6)

```

```{r}
## KM plot with 75th quantile

# Compute sample sizes for each CAlevel group
summary(processed$Candida)

# Select the best percentile based on mtsurv plot (which in this case is 75th)

processed <- processed %>%
  mutate(CAlevel = if_else(Candida <= 1125.25  , "Low", "High")) %>%
  mutate(CAlevel = factor(CAlevel, levels = c("Low", "High")))

fit<- survfit(Surv(diagsurvtime, status)~CAlevel, data = processed)

p<-ggsurvplot(fit,
              data = processed,
              pval=T,
              pval.coord = c(0.155, 0.2),
              risk.table=T,
              xlim = c(0, 5),
              break.x.by = 1,
              xlab="Time (years)",palette = 
                c("#E7B800", "#2E9FDF"),# custom color palettes
              conf.int = TRUE,
              lwd=1.5,font.x = c(15, "bold"),
              font.y = c(15, "bold"),font.tickslab = c(12, "bold"),
              font.legend = c(9),  # Two different colors for CI (light purple and light blue)
              conf.int.alpha = 0.3,
              legend.labs = c("Low Candida (n = 1142)","High Candida (n = 429 )"),
              ggtheme = theme_bw(),
              legend.title = "Abundance   ")

p$plot + 
  labs(title = "NSCLC ORIEN") + 
  theme(
    legend.text = element_text(size = 9, face = "bold"),
    legend.title = element_text(size = 9, face = "bold"),
    legend.position = c(0.72, .25),
  )


## for normal savings

ggsave(filename = "/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/ORIEN_NSCLC_kmplot_5years.png",
       width = 3, height = 3)
ggsave(filename = "/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/ORIEN_NSCLC_kmplot_5years.svg",
       width = 3, height = 3)

```

