---
title: "Radiation_only_Analysis_NSCLCORIEN"
author: "Dipankor Dhrubo"
date: "2025-10-13"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(survival)
library(ggsurvfit)
library(survminer)
library(patchwork)
library(readr)
library(broom)
library(coxphf)
library(forcats)
library(stringr)
```


```{r}

### Loading Radiation only patients dataset

Radiation_data<- readRDS(file= "/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/NSCLC_metadata.rds") |>
  filter(RadiationTherapyInd == "Yes") %>% unique()

Radiation_patient_expression<- readRDS("/fs/ess/PAS1695/projects/exotho/data/Digital_Twins/NSCLC_processed_gene_expression.rds") %>% select(all_of(Radiation_data$sample))

```
```{r}
Radiation_data_Candida <- Radiation_data %>% select(sample,CAlevel,diagsurvtime,status,Candida) %>% unique()

Clinical <- Radiation_data_Candida %>%
  select(sample, diagsurvtime, status) %>%
  dplyr::rename(vitalstatus = status) %>% mutate(days = as.numeric(diagsurvtime)) %>%
  select(-diagsurvtime,sample, days, vitalstatus)

 # Make sure you look at the dataframe first to select the correct columns.

Abundance_data<- Radiation_data_Candida %>% select(sample,Candida)

survoutput <- mt.surv::survivalByQuantile("Candida", Abundance_data, Clinical)

# Removing the NA value

survoutput<- survoutput[complete.cases(survoutput),]

# Creating the plot

survoutput %>% 
  ggplot(aes(x = percentile, y = -log10(pval), color = hazard.direction)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") +
  theme_bw()


Radiation_data<- Radiation_data %>% mutate(CAlevel = ifelse(Candida < 1193, "Low","High")) %>%
  mutate(CAlevel = factor(CAlevel, levels = c("Low", "High")))

```



```{r}

## Survival Analysis on Radiation treated patients 

fit<- survfit(Surv(diagsurvtime, status)~CAlevel, data = Radiation_data)
fit$strata

p<-ggsurvplot(fit,
              data = Radiation_data,
              pval=T,
              pval.coord = c(0.155, 0.2),
              risk.table=T,
              xlim = c(0, 10),
              break.x.by = 1,
              xlab="Time (years)",palette = 
                c("#E7B800", "#2E9FDF"),# custom color palettes
              conf.int = TRUE,
              lwd=1.5,font.x = c(15, "bold"),
              font.y = c(15, "bold"),font.tickslab = c(12, "bold"),
              font.legend = c(15),  # Two different colors for CI (light purple and light blue)
              conf.int.alpha = 0.3,
              legend.labs = c("Low Candida (n = 646)","High Candida (n = 185 )"),
              ggtheme = theme_bw(),
              legend.title = "Abundance   ")

p$plot + 
  labs(title = "NSCLC ORIEN") + 
  theme(
    legend.text = element_text(size = 9, face = "bold"),
    legend.title = element_text(size = 10, face = "bold"),
    legend.position = c(0.62, .85),
  )

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/orien-nsclc_rad-only_ca.svg",
       height = 4, width = 6)
ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/orien-nsclc_rad-only_ca.png",
       height = 4, width = 5.9)

```

```{r}
##Optional figure
km <- 
  survfit2(Surv(diagsurvtime, status) ~ CAlevel,
           data = Radiation_data) |>
  ggsurvfit(linewidth = 1) +
  labs(title = "",
       x = "Time (Years)", y = "Survival (%)") +
  theme_bw(base_size = 9) +
  theme(
    legend.position = c(0.325, 0.2)
  ) +
  add_confidence_interval() +
  scale_ggsurvfit() +
  xlim(0, 10) +
  scale_color_viridis_d()


km

ggsave("../figures/orien-crc_rad-only_ca.svg",
       height = 2, width = 2.8)
ggsave("../figures/orien-crc_rad-only_ca.png",
       height = 2, width = 2.6)
```

```{r}
km + 
  add_pvalue()

ggsave("../figures/orien-crc_rad-only_ca_w-pval.png",
       height = 3, width = 4)

```


# Cox Regression and forestplot

```{r}

df <- 
  Radiation_data %>%
  filter(complete.cases(diagsurvtime, status, Age, BMI, CAlevel, Stage, Sex)) |> 
  filter(!Stage == "Unknown") |> 
  filter(!BMI == "Unknown/Not Applicable") |> 
  filter(!Sex == "Unknown") |> 
  mutate(stage = if_else(grepl("^I$|^II$", Stage),
                         true = "Early", 
                         false = "Advanced Disease"),
         BMI = as.numeric(BMI)) |> 
  mutate(stage = fct_relevel(stage, "Early"))

```


```{r}

fit.multi <- coxph(Surv(diagsurvtime, status) ~ CAlevel + Age + BMI + stage + Sex, 
                    data = df)

summary(fit.multi)

```

```{r}
coxresults <- broom::tidy(fit.multi, exponentiate = TRUE, conf.int = TRUE)


# Forestplot Creation

coxresults <- coxresults %>% filter(term != "SexUnknown") |>
  mutate(term = forcats::fct_rev(term)) ## Making things in reverse order

coxresults <- coxresults %>%
  mutate(pval_label = sprintf("p = %.3f", p.value)) # Defining 


coxresults_labeled <- coxresults %>%
  mutate(term = as.character(term)) %>%
  mutate(
    term = str_replace(term, "^CAlevel", "Candida Abundance: "),
    term = str_replace(term, "^stage",   "Stage: "),
    term = str_replace(term, "^Sex",     "Sex: "),
    term = str_replace(term, "^Age",     "Age: "),
    term = str_replace(term, "^BMI",     "BMI: ")
  ) %>%
  mutate(term = factor(term))


# Calculate a constant x-position to place all p-values
x_position <- max(coxresults_labeled$conf.high, na.rm = TRUE) * 1.5

# Create the forest plot
ggplot(coxresults_labeled, aes(x = estimate, y = term)) +
  geom_point(size = 1.5) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_text(aes(x = x_position, label = pval_label), hjust = -.25, size = 3.5) +
  scale_x_log10(expand = expansion(mult = c(0.05, 0.6))) +
  labs(x = "Hazard Ratio (95% CI)", y = "Predictor", title = "ORIEN_NSCLC: Radiation Treated Patients") +
  theme_bw()+theme(axis.text.x = element_text(face="bold", size=12),
                   axis.text.y = element_text(face="bold", size=12),
                   axis.title=element_text(size=10,face="bold"))

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Forestplot_Radiationpatients_NSCLC.svg", 
       height = 4, width = 7)

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Forestplot_Radiationpatients_NSCLC.png", 
       height = 4, width = 6.7)
```

```{r}
## Squamous Cell Carcinoma

Radiation_data<- readRDS(file= "/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Data/NSCLC_metadata.rds") |>
  filter(RadiationTherapyInd == "Yes") %>% unique()

Radiation_data_Candida <- Radiation_data %>% select(sample,CAlevel,diagsurvtime,status,Candida, Histology) %>% unique()

Radiation_data_Candida<- Radiation_data_Candida %>% mutate(CAlevel = ifelse(Candida < 1193, "Low","High")) %>%
  mutate(CAlevel = factor(CAlevel, levels = c("Low", "High"))) %>%
  filter(Histology %in% c("Squamous Cell Carcinoma", "Adenocarcinoma")) %>% droplevels()


## For squamous cell carcinoma
fit<- survfit(Surv(diagsurvtime, status)~CAlevel, data = Radiation_data_Candida %>% filter(Histology == "Squamous Cell Carcinoma"))
fit$strata

p<-ggsurvplot(fit,
              data = Radiation_data_Candida %>% filter(Histology == "Squamous Cell Carcinoma"),
              pval=T,
              pval.coord = c(0.155, 0.2),
              risk.table=T,
              xlim = c(0, 10),
              break.x.by = 1,
              xlab="Time (years)",palette = 
                c("#E7B800", "#2E9FDF"),# custom color palettes
              conf.int = TRUE,
              lwd=1.5,font.x = c(15, "bold"),
              font.y = c(15, "bold"),font.tickslab = c(12, "bold"),
              font.legend = c(15),  # Two different colors for CI (light purple and light blue)
              conf.int.alpha = 0.3,
              legend.labs = c("Low Candida (n = 155)","High Candida (n = 50 )"),
              ggtheme = theme_bw(),
              legend.title = "Abundance   ")

p$plot + 
  labs(title = "Squamous NSCLC ORIEN") + 
  theme(
    legend.text = element_text(size = 9, face = "bold"),
    legend.title = element_text(size = 10, face = "bold"),
    legend.position = c(0.62, .85),
  )

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Squamous/AllRadiation_only_kmplot.png", height = 4, width = 5.9)

### Cox_regression forest plot

df_Sq <- 
  Radiation_data %>% filter(Histology == "Squamous Cell Carcinoma") %>%
  filter(complete.cases(diagsurvtime, status, Age, BMI, CAlevel, Stage, Sex)) |> 
  #filter(!Stage == "Unknown") |> 
  #filter(!BMI == "Unknown/Not Applicable") |> 
  #filter(!Sex == "Unknown") |> droplevels() %>%
  mutate(stage = if_else(grepl("^I$|^II$", Stage),
                         true = "Early", 
                         false = "Advanced Disease"),
         BMI = as.numeric(BMI)) |> 
  mutate(stage = fct_relevel(stage, "Early"))

fit.multi <- coxph(Surv(diagsurvtime, status) ~ CAlevel + Age + BMI + stage + Sex, 
                    data = df_Sq)

summary(fit.multi)


# Forestplot Creation for Squamous carcinoma

coxresults <- broom::tidy(fit.multi, exponentiate = TRUE, conf.int = TRUE)

coxresults <- coxresults %>% filter(term != "SexUnknown") |>
  mutate(term = forcats::fct_rev(term)) ## Making things in reverse order

coxresults <- coxresults %>%
  mutate(pval_label = sprintf("p = %.3f", p.value)) # Defining 


coxresults_labeled <- coxresults %>%
  mutate(term = as.character(term)) %>%
  mutate(
    term = str_replace(term, "^CAlevel", "Candida Abundance: "),
    term = str_replace(term, "^stage",   "Stage: "),
    term = str_replace(term, "^Sex",     "Sex: "),
    term = str_replace(term, "^Age",     "Age: "),
    term = str_replace(term, "^BMI",     "BMI: ")
  ) %>%
  mutate(term = factor(term))


# Calculate a constant x-position to place all p-values
x_position <- max(coxresults_labeled$conf.high, na.rm = TRUE) * 1.5

# Create the forest plot
ggplot(coxresults_labeled, aes(x = estimate, y = term)) +
  geom_point(size = 1.5) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_text(aes(x = x_position, label = pval_label), hjust = -.25, size = 3.5) +
  scale_x_log10(expand = expansion(mult = c(0.05, 0.6))) +
  labs(x = "Hazard Ratio (95% CI)", y = "Predictor", title = "ORIEN_SquamousNSCLC: Radiation Treated Patients") +
  theme_bw()+theme(axis.text.x = element_text(face="bold", size=12),
                   axis.text.y = element_text(face="bold", size=12),
                   axis.title=element_text(size=10,face="bold"))

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Squamous/Forestplot_Radiationpatients_NSCLC.svg", 
       height = 4, width = 7)

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Squamous/Forestplot_Radiationpatients_NSCLC.png", 
       height = 4, width = 6.7)

```

```{r}
## For Adrenocarcinoma

fit<- survfit(Surv(diagsurvtime, status)~CAlevel, data = Radiation_data_Candida %>% filter(Histology == "Adenocarcinoma"))
fit$strata

p<-ggsurvplot(fit,
              data = Radiation_data_Candida %>% filter(Histology == "Adenocarcinoma"),
              pval=T,
              pval.coord = c(0.155, 0.2),
              risk.table=T,
              xlim = c(0, 10),
              break.x.by = 1,
              xlab="Time (years)",palette = 
                c("#E7B800", "#2E9FDF"),# custom color palettes
              conf.int = TRUE,
              lwd=1.5,font.x = c(15, "bold"),
              font.y = c(15, "bold"),font.tickslab = c(12, "bold"),
              font.legend = c(15),  # Two different colors for CI (light purple and light blue)
              conf.int.alpha = 0.3,
              legend.labs = c("Low Candida (n = 371)","High Candida (n = 101 )"),
              ggtheme = theme_bw(),
              legend.title = "Abundance   ")

p$plot + 
  labs(title = "Arenocarcinoma NSCLC ORIEN") + 
  theme(
    legend.text = element_text(size = 9, face = "bold"),
    legend.title = element_text(size = 10, face = "bold"),
    legend.position = c(0.62, .85),
  )

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Adenocarcinoma/AllRadiation_only_kmplot.png", height = 4, width = 5.9)

df_Ad <- 
  Radiation_data %>% filter(Histology == "Adenocarcinoma") %>%
  filter(complete.cases(diagsurvtime, status, Age, BMI, CAlevel, Stage, Sex)) |> 
  #filter(!Stage == "Unknown") |> 
  #filter(!BMI == "Unknown/Not Applicable") |> 
  #filter(!Sex == "Unknown") |> droplevels() %>%
  mutate(stage = if_else(grepl("^I$|^II$", Stage),
                         true = "Early", 
                         false = "Advanced Disease"),
         BMI = as.numeric(BMI)) |> 
  mutate(stage = fct_relevel(stage, "Early"))

fit.multi <- coxph(Surv(diagsurvtime, status) ~ CAlevel + Age + BMI + stage + Sex, 
                    data = df_Ad)

summary(fit.multi)

# Forestplot Creation for Squamous carcinoma

coxresults <- broom::tidy(fit.multi, exponentiate = TRUE, conf.int = TRUE)

coxresults <- coxresults %>% filter(term != "SexUnknown") |>
  mutate(term = forcats::fct_rev(term)) ## Making things in reverse order

coxresults <- coxresults %>%
  mutate(pval_label = sprintf("p = %.3f", p.value)) # Defining 


coxresults_labeled <- coxresults %>%
  mutate(term = as.character(term)) %>%
  mutate(
    term = str_replace(term, "^CAlevel", "Candida Abundance: "),
    term = str_replace(term, "^stage",   "Stage: "),
    term = str_replace(term, "^Sex",     "Sex: "),
    term = str_replace(term, "^Age",     "Age: "),
    term = str_replace(term, "^BMI",     "BMI: ")
  ) %>%
  mutate(term = factor(term))


# Calculate a constant x-position to place all p-values
x_position <- max(coxresults_labeled$conf.high, na.rm = TRUE) * 1.5

# Create the forest plot
ggplot(coxresults_labeled, aes(x = estimate, y = term)) +
  geom_point(size = 1.5) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_text(aes(x = x_position, label = pval_label), hjust = -.25, size = 3.5) +
  scale_x_log10(expand = expansion(mult = c(0.05, 0.6))) +
  labs(x = "Hazard Ratio (95% CI)", y = "Predictor", title = "ORIEN_AdrenoNSCLC: Radiation Treated Patients") +
  theme_bw()+theme(axis.text.x = element_text(face="bold", size=12),
                   axis.text.y = element_text(face="bold", size=12),
                   axis.title=element_text(size=10,face="bold"))

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Squamous/Forestplot_Radiationpatients_NSCLC.svg", 
       height = 4, width = 7)

ggsave("/users/PAS1695/dipankor99/Github/digital-twins/exploratory/Figures/Adenocarcinoma/Forestplot_Radiationpatients_NSCLC.png", 
       height = 4, width = 6.7)

```
